# fly.toml app configuration file generated for storytelling-chatbot-autumn-paper-5255 on 2024-06-29T16:30:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'storytelling-chatbot-autumn-paper-5255'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
