# fly.toml app configuration file generated for terifai-empty-fog-1961 on 2024-07-10T19:26:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'terifai-empty-fog-1961'
primary_region = 'yyz'

[build]

[env]
  WHEEL = '${WHEEL}'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
